 1D array
 

In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))




[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
#reshaping one dimensional array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

2D array

In [7]:
arr3=np.array([[1,2,3,4],[5,6,8,9]])
print(arr3)
print(arr3.shape)
np.arange(0,10)#means elements in between 0 to 10
np.arange(0,8,3)
np.reshape(5,1)#5 row 1 column


[[1 2 3 4]
 [5 6 8 9]]
(2, 4)


array([5])

In [8]:
arr4=np.array([[1,2,3,4],[5,6,8,9]])
new_arr=np.reshape(arr4,(4,2))
print(new_arr)

[[1 2]
 [3 4]
 [5 6]
 [8 9]]


Inbuilds function in numpy array


In [9]:
np.ones((3,5))#used to create two dimension array of 3 rows and 5 columns


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
##Attributes of numpy array
arr=np.array([[1,2,3,4,5],[2,3,4,5,5]])
print("number of dimension",arr.ndim)
print("size of elements",arr.size)
print("data types",arr.dtype)
print("item size in bytes",arr.itemsize)

number of dimension 2
size of elements 10
data types int64
item size in bytes 8


Numpy vectorized operation


In [12]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("addition",arr1 + arr2)
print("subtractin",arr1 - arr2)
print("multiplication",arr1 * arr2)
print("division",arr1 / arr2)


addition [11 22 33 44 55]
subtractin [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [13]:
####universal array
arr=np.array([10,20,30])
print(np.sin(arr))
print(np.cos(arr))
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))


[-0.54402111  0.91294525 -0.98803162]
[-0.83907153  0.40808206  0.15425145]
[3.16227766 4.47213595 5.47722558]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]
[2.30258509 2.99573227 3.40119738]


In [14]:
###array slicing
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)
print(arr[1:,3:])#row,column
print(arr[0][1])
print(arr[0:2,2:])#start at row 0 and end at row 2,column

[[1 2 3 4 5]
 [5 6 7 8 9]]
[[8 9]]
2
[[3 4 5]
 [7 8 9]]


In [15]:
##Modify array elements
arr[0,1]=56
print(arr)

[[ 1 56  3  4  5]
 [ 5  6  7  8  9]]


In [16]:
arr[1:]=20
print(arr)

[[ 1 56  3  4  5]
 [20 20 20 20 20]]


In [ ]:
###Normalization 
##to have a mean of 0 and standard deviation of 1
data=np.array([10,22,33,44])
mean=np.mean(data)
standard_dev=np.std(data)
normalized_data=(data-mean)/standard_dev
print(normalized_data)


[-1.36506596 -0.41545486  0.45502199  1.32549884]


In [ ]:
###statistical concept in numpy
data=([1,2,3,4,6,])
mean=print(np.mean(data))
standard_dev=print(np.std(data))
median=print(np.median(data))






3.2
1.7204650534085253
3.0


In [ ]:
##logical operations
data=np.array([1,2,3,4,5,55,6])
print(data>5)
print(data[(data > 5) & (data < 8)])#and doesn't work


[False False False False False  True  True]
[6]
